version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    hostname: backend
    volumes:
      - ./:/home/app
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    networks:
      - app_net
    restart: always

  web:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  postgres:
    image: postgres:13.6-alpine3.15
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    networks:
      - app_net
    restart: always

networks:
  app_net:

volumes: 
  postgres_data: 
  redis_data: 
  media_volume: 